name: Deploy — Terraform Apply

on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  TF_WORKDIR: infra

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_api_id: ${{ secrets.ML_API_ID }}
      TF_VAR_cloudfront_distribution_id: ${{ secrets.ML_CF_DISTRIBUTION_ID }}
      TF_VAR_serverless_memory_mb: ${{ secrets.ML_SERVERLESS_MEMORY_MB }}
      TF_VAR_serverless_max_conc: ${{ secrets.ML_SERVERLESS_MAX_CONC }}

    defaults:
      run:
        working-directory: ${{ env.TF_WORKDIR }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::097635932419:role/ml-sagemaker-serverless-gha-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform init
        run: terraform init -upgrade -input=false

      - name: Terraform plan
        run: terraform plan -input=false -lock=false

      - name: Terraform apply
        run: terraform apply -auto-approve -input=false
